#Take Input Matrix :

In [18]:
rows = int(input("How many rows you want: "))
col = int(input("How many columns you want: "))

matrix = []
print("Entries the matrix row-wise:")

for i in range(rows):
    row = []
    for j in range(col):
        row.append(int(input()))
    matrix.append(row)

print("\n2D matrix is:")

for i in range(rows):
    for j in range(col):
        print(matrix[i][j], end=" ")
    print()

How many rows you want: 2
How many columns you want: 2
Entries the matrix row-wise:
1
2
3
4

2D matrix is:
1 2 
3 4 


#Addition, Subtraction, Multiplication, Division of matrix

In [19]:
x = [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]

y = [[9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]]

add_res = [[x[i][j] + y[i][j] for j in range(len(x[0]))] for i in range(len(x))]

sub_res = [[x[i][j] - y[i][j] for j in range(len(x[0]))] for i in range(len(x))]

mult_res = [[x[i][j] * y[i][j] for j in range(len(x[0]))] for i in range(len(x))]

div_res = [[x[i][j] // y[i][j] for j in range(len(x[0]))] for i in range(len(x))]

print("Matrix Addition:")
for row in add_res:
    print(row)

print("\nMatrix Subtraction:")
for row in sub_res:
    print(row)

print("\nMatrix Multiplication:")
for row in mult_res:
    print(row)

print("\nMatrix Division:")
for row in div_res:
    print(row)

Matrix Addition:
[10, 10, 10]
[10, 10, 10]
[10, 10, 10]

Matrix Subtraction:
[-8, -6, -4]
[-2, 0, 2]
[4, 6, 8]

Matrix Multiplication:
[9, 16, 21]
[24, 25, 24]
[21, 16, 9]

Matrix Division:
[0, 0, 0]
[0, 1, 1]
[2, 4, 9]


#Transpose of a Matrix

x = [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]



In [20]:
transpose = [[0]*3 for _ in range(3)]

for i in range(len(x)):
    for j in range(len(x[0])):
        transpose[j][i] = x[i][j]

for r in transpose:
    print(r)

[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


#NumPy Matrix Operations
##Addition, Subtraction, Multiplication, Division of matrix

In [21]:
import numpy as np

x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Addition:\n", np.add(x, y))
print()
print("Subtraction:\n", np.subtract(x, y))
print()
print("Multiplication:\n", np.multiply(x, y))
print()
print("Division:\n", np.divide(x, y))

Addition:
 [[ 8 10]
 [13 15]]

Subtraction:
 [[-6 -6]
 [-5 -5]]

Multiplication:
 [[ 7 16]
 [36 50]]

Division:
 [[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


##Dot and cross product with Matrix

In [22]:
x = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
y = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

print("Dot Product:\n", np.dot(x, y))
print()
print("Cross Product:\n", np.cross(x, y))

Dot Product:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Cross Product:
 [[-10  20 -10]
 [-10  20 -10]
 [-10  20 -10]]


##Transpose of a Matrix

In [23]:
matrix = [[1, 2, 3], [4, 5, 6]]
print(np.transpose(matrix))

[[1 4]
 [2 5]
 [3 6]]


##Slicing in Matrix using Numpy

In [24]:
x = np.array([[6, 8, 10],
              [9, -12, 15],
              [12, 16, 20],
              [15, -20, 25]])

print("Full Matrix:\n", x)
print("Third Row, Second Column:", x[2:3, 1])
print("Third Row, Third Column:", x[2:3, 2])

Full Matrix:
 [[  6   8  10]
 [  9 -12  15]
 [ 12  16  20]
 [ 15 -20  25]]
Third Row, Second Column: [16]
Third Row, Third Column: [20]


##Deleting Rows and Columns with NumPy

In [25]:
a = np.array([[6, 8, 10],
              [9, -12, 15],
              [12, 16, 20],
              [15, -20, 25]])

print("Delete 0th Row:\n", np.delete(a, 0, axis=0))
print()
print("Delete 1st Columns:\n", np.delete(a, 1, axis=1))

Delete 0th Row:
 [[  9 -12  15]
 [ 12  16  20]
 [ 15 -20  25]]

Delete 1st Columns:
 [[ 6 10]
 [ 9 15]
 [12 20]
 [15 25]]
