<a href="https://colab.research.google.com/github/mdsozon24/100-days-of-ML-AI-challenge/blob/main/Math/Probability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Probability: Joint vs. Marginal vs. Conditional

In [ ]:
data = [
    {'Gender': 'Male', 'Color': 'Blue'},
    {'Gender': 'Female', 'Color': 'Red'},
    {'Gender': 'Male', 'Color': 'Red'},
    {'Gender': 'Female', 'Color': 'Blue'},
    {'Gender': 'Male', 'Color': 'Blue'},
    {'Gender': 'Female', 'Color': 'Red'},
    {'Gender': 'Female', 'Color': 'Blue'},
    {'Gender': 'Male', 'Color': 'Red'},
    {'Gender': 'Female', 'Color': 'Red'},
    {'Gender': 'Male', 'Color': 'Blue'},
]

total_samples = len(data)

joint_counts = {}
for item in data:
    gender_color = (item['Gender'], item['Color'])
    if gender_color not in joint_counts:
        joint_counts[gender_color] = 0
    joint_counts[gender_color] += 1

joint_probabilities = {key: count / total_samples for key, count in joint_counts.items()}

print("Joint Probabilities:")
for key, prob in joint_probabilities.items():
    print(f"P({key[0]} and {key[1]}): {prob}")

print("\n" + "="*30 + "\n")

gender_counts = {}
color_counts = {}

for item in data:
    if item['Gender'] not in gender_counts:
        gender_counts[item['Gender']] = 0
    gender_counts[item['Gender']] += 1

    if item['Color'] not in color_counts:
        color_counts[item['Color']] = 0
    color_counts[item['Color']] += 1

marginal_gender_probabilities = {key: count / total_samples for key, count in gender_counts.items()}
marginal_color_probabilities = {key: count / total_samples for key, count in color_counts.items()}

print("Marginal Probabilities:")
for gender, prob in marginal_gender_probabilities.items():
    print(f"P({gender}): {prob}")
for color, prob in marginal_color_probabilities.items():
    print(f"P({color}): {prob}")

print("\n" + "="*30 + "\n")

conditional_probabilities = {}

for gender in gender_counts:
    for color in color_counts:
        joint_key = (gender, color)
        if joint_key in joint_counts:
            conditional_prob = joint_counts[joint_key] / gender_counts[gender]
            conditional_probabilities[(color, gender)] = conditional_prob
            print(f"P({color} | {gender}): {conditional_prob}")

print("\n")

for color in color_counts:
    for gender in gender_counts:
        joint_key = (gender, color)
        if joint_key in joint_counts:
            conditional_prob = joint_counts[joint_key] / color_counts[color]
            conditional_probabilities[(gender, color)] = conditional_prob
            print(f"P({gender} | {color}): {conditional_prob}")

Joint Probabilities:
P(Male and Blue): 0.3
P(Female and Red): 0.3
P(Male and Red): 0.2
P(Female and Blue): 0.2


Marginal Probabilities:
P(Male): 0.5
P(Female): 0.5
P(Blue): 0.5
P(Red): 0.5


P(Blue | Male): 0.6
P(Red | Male): 0.4
P(Blue | Female): 0.4
P(Red | Female): 0.6


P(Male | Blue): 0.6
P(Female | Blue): 0.4
P(Male | Red): 0.4
P(Female | Red): 0.6


#With Numpy

In [ ]:
import numpy as np
import pandas as pd

data = {
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'Color': ['Blue', 'Red', 'Red', 'Blue', 'Blue', 'Red', 'Blue', 'Red', 'Red', 'Blue']
}

df = pd.DataFrame(data)

contingency_table = pd.crosstab(df['Gender'], df['Color'])
print("Contingency Table:")
display(contingency_table)

print("\n" + "="*30 + "\n")

joint_probabilities_np = contingency_table.values / contingency_table.values.sum()
print("Joint Probabilities (using numpy):")
print(joint_probabilities_np)

print("\n" + "="*30 + "\n")

marginal_gender_probabilities_np = contingency_table.sum(axis=1).values / contingency_table.values.sum()
marginal_color_probabilities_np = contingency_table.sum(axis=0).values / contingency_table.values.sum()

print("Marginal Probabilities (using numpy):")
print("Gender:", marginal_gender_probabilities_np)
print("Color:", marginal_color_probabilities_np)


print("\n" + "="*30 + "\n")

conditional_color_given_gender_np = contingency_table.values / contingency_table.sum(axis=1).values[:, np.newaxis]
print("Conditional Probabilities P(Color | Gender) (using numpy):")
print(conditional_color_given_gender_np)

print("\n")

conditional_gender_given_color_np = contingency_table.values / contingency_table.sum(axis=0).values[np.newaxis, :]
print("Conditional Probabilities P(Gender | Color) (using numpy):")
print(conditional_gender_given_color_np)

Contingency Table:


Color   Blue  Red
Gender           
Female     2    3
Male       3    2



Joint Probabilities (using numpy):
[[0.2 0.3]
 [0.3 0.2]]


Marginal Probabilities (using numpy):
Gender: [0.5 0.5]
Color: [0.5 0.5]


Conditional Probabilities P(Color | Gender) (using numpy):
[[0.4 0.6]
 [0.6 0.4]]


Conditional Probabilities P(Gender | Color) (using numpy):
[[0.4 0.6]
 [0.6 0.4]]
