<a href="https://colab.research.google.com/github/mdsozon24/100-days-of-ML-AI-challenge/blob/main/Math/QR_Decomposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#QR Decomposition using Python

In [2]:
import numpy as np

arr = np.array([[1, 2, 4],
                [0, 0, 5],
                [0, 3, 6]])
print(arr)

q, r = np.linalg.qr(arr)
print('\nQ:\n', q)
print()
print('\nR:\n', r)
print()
print(np.allclose(arr, np.dot(q, r)))

[[1 2 4]
 [0 0 5]
 [0 3 6]]

Q:
 [[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0. -1.  0.]]


R:
 [[ 1.  2.  4.]
 [ 0. -3. -6.]
 [ 0.  0. -5.]]

True
