<a href="https://colab.research.google.com/github/mdsozon24/100-days-of-ML-AI-challenge/blob/main/Math/Singular_Value_Decomposition_(SVD).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Singular Value Decomposition (SVD)

In [2]:
import numpy as np

A = np.array([[3, 1],
              [1, 3],
              [1, 1]], dtype=float)

U, S, Vt = np.linalg.svd(A, full_matrices=False)

print("Matrix U:\n", U)
print()
print("Singular values (Sigma):\n", S)
print()
print("Matrix V^T:\n", Vt)
print()

Sigma = np.diag(S)
A_reconstructed = np.dot(U, np.dot(Sigma, Vt))
print("Reconstructed A:\n", np.round(A_reconstructed, 4))


Matrix U:
 [[-6.66666667e-01  7.07106781e-01]
 [-6.66666667e-01 -7.07106781e-01]
 [-3.33333333e-01  5.92577380e-18]]

Singular values (Sigma):
 [4.24264069 2.        ]

Matrix V^T:
 [[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]

Reconstructed A:
 [[3. 1.]
 [1. 3.]
 [1. 1.]]
